#[cfg(target_arch = "wasm32")]
pub(crate) mod automove_deadline;
#[cfg(target_arch = "wasm32")]
pub(crate) mod automove_exact;
#[cfg(target_arch = "wasm32")]
pub(crate) mod automove_turn_engine;
#[cfg(any(target_arch = "wasm32", test))]
pub(crate) mod available_move_kind;
pub(crate) mod board;
pub(crate) mod color;
pub(crate) mod config;
pub(crate) mod consumable;
pub(crate) mod event;
pub(crate) mod fen_representable;
pub(crate) mod input;
pub(crate) mod item;
pub(crate) mod location;
pub(crate) mod mana;
pub(crate) mod mon;
pub(crate) mod mons_game;
#[cfg(any(target_arch = "wasm32", test))]
pub(crate) mod mons_game_model;
pub(crate) mod next_input;
pub(crate) mod output;
#[cfg(target_arch = "wasm32")]
pub(crate) mod scoring;
pub(crate) mod square;
#[cfg(target_arch = "wasm32")]
pub(crate) use automove_exact::*;
#[cfg(target_arch = "wasm32")]
pub(crate) use automove_turn_engine::*;
#[cfg(any(target_arch = "wasm32", test))]
pub(crate) use available_move_kind::*;
pub(crate) use board::*;
pub(crate) use color::*;
pub(crate) use config::*;
pub(crate) use consumable::*;
pub(crate) use event::*;
pub(crate) use fen_representable::*;
pub(crate) use input::*;
pub(crate) use item::*;
pub(crate) use location::*;
pub(crate) use mana::*;
pub(crate) use mon::*;
pub(crate) use mons_game::*;
#[cfg(any(target_arch = "wasm32", test))]
pub(crate) use mons_game_model::*;
pub(crate) use next_input::*;
pub(crate) use output::*;
pub(crate) use square::*;
pub(crate) use wasm_bindgen::prelude::*;
